['progr', 
	['pdecls', 
		['stmts', 
			['pdecl', ('identifier', 'p1')], 
			['pdecl', ('identifier', 'p2')], 
			['pdecl', ('identifier', 'p3')], 
			['pdecl', ('identifier', 'p')], 
			['pdecl', ('identifier', 'q1')], 
			['pdecl', ('identifier', 'q2')], 
			['pdecl', ('identifier', 'q3')], 
			['pdecl', ('identifier', 'r')]]], 
	['rules', 
		['stmts', 
			['fact', 
				['head', 
					['unit', ['literal', ['patom', ('identifier', 'p1')]]]]], 
			['fact', 
				['head', 
					['disj', 
						['disj', 
							['unit', ['literal', ['patom', ('identifier', 'p1')]]], 
							['unit', ['literal', ['patom', ('identifier', 'p2')]]]], 
						['unit', ['literal', ['patom', ('identifier', 'p3')]]]]]], 
			['long_rule', 
				['head', 
					['unit', ['literal', ['patom', ('identifier', 'p')]]]], 
				['body', 
					['unit', ['literal', ['patom', ('identifier', 'q1')]]]]], 
			['long_rule', 
				['head', 
					['unit', ['literal', ['patom', ('identifier', 'p')]]]], 
				['body', 
					['conj', 
						['conj', 
							['unit', ['literal', ['patom', ('identifier', 'q1')]]], 
							['literal', ['patom', ('identifier', 'q2')]]], 
						['literal', ['patom', ('identifier', 'q3')]]]]], 
			['long_rule', 
				['head', 
					['unit', ['literal', ['patom', ('identifier', 'p')]]]], 
				['body', 
					['unit', ['not_literal', ['patom', ('identifier', 'r')]]]]]]]]
	
['progr', ['pdecls', ['stmts', ['pdecl', ('identifier', 'p1')], ['pdecl', ('identifier', 'p2')], ['pdecl', ('identifier', 'p3')], ['pdecl', ('identifier', 'p')], ['pdecl', ('identifier', 'q1')], ['pdecl', ('identifier', 'q2')], ['pdecl', ('identifier', 'q3')], ['pdecl', ('identifier', 'r')]]], ['rules', ['stmts', ['fact', ['head', ['unit', ['literal', ['patom', ('identifier', 'p1')]]]]], ['fact', ['head', ['disj', ['disj', ['unit', ['literal', ['patom', ('identifier', 'p1')]]], ['unit', ['literal', ['patom', ('identifier', 'p2')]]]], ['unit', ['literal', ['patom', ('identifier', 'p3')]]]]]], ['long_rule', ['head', ['unit', ['literal', ['patom', ('identifier', 'p')]]]], ['body', ['unit', ['literal', ['patom', ('identifier', 'q1')]]]]], ['long_rule', ['head', ['unit', ['literal', ['patom', ('identifier', 'p')]]]], ['body', ['conj', ['conj', ['unit', ['literal', ['patom', ('identifier', 'q1')]]], ['literal', ['patom', ('identifier', 'q2')]]], ['literal', ['patom', ('identifier', 'q3')]]]]], ['long_rule', ['head', ['unit', ['literal', ['patom', ('identifier', 'p')]]]], ['body', ['unit', ['not_literal', ['patom', ('identifier', 'r')]]]]]]]]
